### ISSUE TITLE
When you use the query builder it doesn't default to searching the whole collection.

### ISSUE THREAD

**Issue by jjfiv** [CIIR/Proteus#111]

**Comment by mzarozinski** [comment]
fixed in:

Branch: refs/heads/tagging
  Home:   https://github.com/CIIR/Proteus
  Commit: 7eb21800a68a5defb0cb132ecf700c40456fe2f5
      https://github.com/CIIR/Proteus/commit/7eb21800a68a5defb0cb132ecf700c40456fe2f5
  Author: mzarozinski <MichaelZ@cs.umass.edu>
  Date:   2016-05-17 (Tue, 17 May 2016)

  Changed paths:
    M homer/web/css/style.css
    M homer/web/index.html
    M homer/web/js/ui.js

  Log Message:
  -----------
  Updated query builder so it searches all without restriction.
