### ISSUE TITLE
about interesting results

### ISSUE THREAD

**Issue by efcan** [CIIR/Proteus#55]
when I query author:"r. manmatha" it does not bring anything; however,when I do
abstract:"video retrieval" I got results containing "video" "video retrieval" and "retrieval".
I believe it does not do exact matching for the latter case but it does for the first case

**Comment by mzarozinski** [comment]
author:"r manmatha" (without the period) will return results, the query processor should strip off the period.

**Comment by mzarozinski** [comment]
The results for just "video" and "retrieval" are because the query gets expanded to: 

Original Query	abstract:"video retrieval"

Parsed Query	#combine:w=1.0( #inside( #ordered:1( #extents:video:part=postings.krovetz() #extents:retrieval:part=postings.krovetz() ) #extents:abstract:part=extents() ) )

Transformed Query	#combine:w=1.0( #dirichlet:avgLength=3721.6215806652162:collectionLength=574677918:documentCount=154416:maximumCount=4:nodeFrequency=185:w=1.0( #lengths:document:part=lengths() #inside( #ordered:1( #extents:video:part=postings.krovetz() #extents:retrieval:part=postings.krovetz() ) #extents:abstract:part=extents() ) ) )

**Comment by j-allan** [comment]
I'd say the example below is a clinching argument for not having any 
person use Galago's query "language".

I have absolutely no idea why that explains what happened. It looks like 
/video/ and /retrieval/ are inside a #1 operator so it ought to require 
both.

**Comment by mzarozinski** [comment]
After some digging, this is due to the called hasMatch() is in the base class which (almost) always returns true causing each document to have individual terms dirichlet scored. 

I have a local (hacked for now) fix for the #od operator, but now the #inside operator needs it's hasMatch method fixed.

**Comment by mzarozinski** [comment]
"video retrieval" issue fixed in Galago commit: https://sourceforge.net/p/lemur/galago/ci/652d4aaa143620d9a4ceb99e0f1cb2d145e953ff/

**Comment by mzarozinski** [comment]
Fixed the author:"r manmatha" issue. Fixes in Galago core are in commit: https://sourceforge.net/p/lemur/galago/ci/b1ae4bfa52d92930af7fdba33d72ee42b76f85d1/

Proteus specific updates are in commit: https://github.com/CIIR/Proteus/commit/e9a6e8d0a7dc9fd992a27724542ab5e1159fef10
