### ISSUE TITLE
Spelling error in the parsed title

### ISSUE THREAD

**Issue by mhjang** [CIIR/Proteus#74]
I found a paper whose title is "Efcient Keyword Extractionfor Meaningful Document Perception". In the original paper there was no any spelling error such as in "eficient". I don't know how this discrepancy has caused when I assumed that the titles were rather parsed but not typed manually... maybe there was an error at the time of the papers being parsed and the ACM library changed it afterwards? 

I'm just leaving a note in case there is a bug in the pipeline since I don't know the details of the system.

**Comment by mzarozinski** [comment]
This appears to be an issue caused by the pstotext step (https://github.com/CIIR/rexa1-pstotext), it "read" the title as:

<page n="1"><line>
<tbox llx="181" lly="701" urx="272" ury="724" f="1"><![CDATA[Ef^cient]]></tbox>
<tbox llx="257" lly="701" urx="351" ury="724" f="1"><![CDATA[ Keyword]]></tbox>
<tbox llx="336" lly="701" urx="444" ury="724" f="1"><![CDATA[ Extraction]]></tbox>
</line>
